# Config file for the wallpaper manager

# Wallpaper selection to be used by the built-in monitor
wallpaper {
  # Monitor to display this wallpaper on
  monitor = eDP-1

  # Path to an image or image directory
  path = /home/mg/Pictures/Wallpapers/Hermitcraft/

  # Determines how to display the image [contain|cover|tile|fill]
  fit_mode = cover

  # Time in seconds between wallpaper changes
  timeout = 3600
}

# Wallpaper to be used by other monitors (namely the really wide one)
wallpaper {
  monitor = 
  path = /home/mg/Pictures/Wallpapers/OlympicWallpaper.jpg
  fit_mode = cover
}

# Disable the hyprland splash at the bottom of the screen
splash = false
