# Hyprland's screen locking utility

font = BigBlueTerm437 Nerd Font Mono

general {
  hide_cursor = true
  ignore_empty_input = true
}

auth {
  fingerprint { 
    enabled = true
    ready_message = Place your right index finger on the reader
    present_message = ...
    retry_delay = 250
  }
}

animations {
    enabled = false
    bezier = linear, 1, 1, 0, 0
    animation = fadeIn, 1, 5, linear
    animation = fadeOut, 1, 5, linear
    animation = inputFieldDots, 1, 2, linear
}

background {
    monitor =
    color = rgb(28, 28, 28)
}

input-field {
    monitor = eDP-1
    size = 35%, 5%
    outline_thickness = 8
    inner_color = rgba(0, 0, 0, 0.0) # no fill

    outer_color = rgba(b19e7fee)
    fail_color = rgba(f5402dee)

    font_color = rgba(b19e7fee)
    fade_on_empty = false
    rounding = 0

    font_family = BigBlueTerm437 Nerd Font Propo
    placeholder_text = Place your right index finger on the reader
    fail_text = $PAMFAIL$FPRINTFAIL

    dots_text_format = *
    dots_size = 0.4
    dots_spacing = 0.3

    position = 0, 0
    halign = center
    valign = center 
}

# TIME
label {
    monitor = eDP-1
    text = $TIME12 # update every 60 seconds
    font_size = 16
    font_family = BigBlueTerm437 Nerd Font Propo
    color = rgba(b19e7fee) 

    position = 0, 5%
    halign = center
    valign = center
}
